import { useState } from 'react';
import Markdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import remarkGfm from 'remark-gfm';

/**
 * A single chat turn. User messages render as a right-aligned bubble; assistant
 * messages render as full-width Markdown, matching the convention used by most
 * chat UIs (it gives long answers, tables and code the full column width).
 *
 * @param {Object} props
 * @param {'user'|'assistant'} props.role Author.
 * @param {string} props.content Message text, Markdown for assistant turns.
 * @param {boolean} [props.streaming] Whether to show the blinking caret.
 * @param {number} [props.inputTokens] Prompt tokens billed for this turn.
 * @param {number} [props.outputTokens] Completion tokens billed for this turn.
 * @param {{inputPerMillion: number, outputPerMillion: number}} [props.pricing] Rates
 *   for the conversation's model, used for the indicative cost.
 */
export default function Message({
  role,
  content,
  streaming = false,
  inputTokens = 0,
  outputTokens = 0,
  pricing = null,
}) {
  if (role === 'user') {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] whitespace-pre-wrap break-words rounded-2xl bg-zinc-800 px-4 py-2.5 text-[15px] leading-relaxed">
          {content}
        </div>
      </div>
    );
  }

  // Usage is only known once the turn completes, and older stored turns predate
  // the counters, so the footer stays absent rather than showing zeros.
  const showUsage = !streaming && (inputTokens > 0 || outputTokens > 0);

  return (
    <div className="group/msg">
      <div className={`prose-chat ${streaming ? 'streaming-caret' : ''}`}>
        <Markdown
          remarkPlugins={[remarkGfm]}
          rehypePlugins={[rehypeHighlight]}
          components={{ pre: CodeBlock }}
        >
          {content}
        </Markdown>
      </div>

      {showUsage && <UsageFooter
        inputTokens={inputTokens}
        outputTokens={outputTokens}
        pricing={pricing}
      />}
    </div>
  );
}

/**
 * Per-turn token usage, revealed on hover so it stays out of the way while
 * reading. The row keeps its height at all times so hovering does not nudge the
 * conversation.
 *
 * @param {{inputTokens: number, outputTokens: number, pricing: Object|null}} props
 */
function UsageFooter({ inputTokens, outputTokens, pricing }) {
  const cost = estimateCost(inputTokens, outputTokens, pricing);

  return (
    <div className="mt-1 h-4 select-none text-xs text-zinc-600 opacity-0 transition-opacity duration-150 group-hover/msg:opacity-100">
      <span title="Prompt tokens, which include the conversation history resent each turn">
        {inputTokens.toLocaleString()} in
      </span>
      {' · '}
      <span title="Tokens generated by the model for this reply">
        {outputTokens.toLocaleString()} out
      </span>
      {cost && <span title="Indicative only: based on published list rates and excluding prompt caching">
        {' · '}estimated cost {cost}
      </span>}
    </div>
  );
}

/**
 * Indicative turn cost. Returns null below half a cent, since rendering
 * "~$0.00" reads as broken rather than cheap.
 *
 * @param {number} inputTokens Prompt tokens.
 * @param {number} outputTokens Completion tokens.
 * @param {{inputPerMillion: number, outputPerMillion: number}|null} pricing Rates.
 * @returns {string|null} Formatted amount, or null when too small to be useful.
 */
function estimateCost(inputTokens, outputTokens, pricing) {
  if (!pricing) return null;

  const usd =
    (inputTokens / 1_000_000) * pricing.inputPerMillion +
    (outputTokens / 1_000_000) * pricing.outputPerMillion;

  if (usd < 0.005) return null;
  return `~$${usd.toFixed(2)}`;
}

/**
 * Fenced code block with a copy button.
 *
 * @param {{children: React.ReactNode}} props Rendered `pre` content.
 */
function CodeBlock({ children }) {
  const [copied, setCopied] = useState(false);

  async function copy(event) {
    // The rendered markup is the reliable source of the code text; reaching into
    // the React children tree is brittle across plugin versions.
    const code = event.currentTarget.parentElement?.querySelector('code')?.innerText ?? '';
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard access can be denied; silently leave the button unchanged.
    }
  }

  return (
    <div className="group relative">
      <pre>{children}</pre>
      <button
        type="button"
        onClick={copy}
        className="absolute right-2 top-2 rounded border border-surface-border bg-zinc-800/90 px-2 py-1 text-xs text-zinc-300 transition hover:bg-zinc-700"
      >
        {copied ? 'Copied' : 'Copy'}
      </button>
    </div>
  );
}
